name: Check patch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: almalinux-9
            shortcut: el9
            container-name: almalinux9
          - name: almalinux-10
            shortcut: el10
            container-name: almalinux10
          - name: centos-stream-9
            shortcut: el9s
            container-name: el9stream
          - name: centos-stream-10
            shortcut: el10s
            container-name: el10stream

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      - name: Trust repository
        run: git config --global --add safe.directory "$(pwd)"

      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install dependencies
        run: dnf install -y autoconf automake gettext-devel git make rpm-build gettext python3-devel ovirt-engine-nodejs-modules python3-pip

      - name: Install python packages
        run: pip install coverage pycodestyle pyflakes

      - name: Check patch
        run: automation/check-patch.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: rpm-${{ matrix.shortcut }}
          path: exported-artifacts

  publish-rpms:
    permissions:
      artifact-metadata: read
    needs: build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ovirt/ovirt-workflows/.github/workflows/publish-rpms.yml@main
    secrets: inherit
